/**
 * Every user-visible string lives here so the UI can be translated later.
 * Keys are grouped by screen/component. Keep labels as plain-English verbs.
 */
export const STRINGS = {
  app: {
    name: 'Smart House',
    tagline: 'Find a house design that fits your plot and your budget.',
    skipToContent: 'Skip to main content',
    loading: 'Loading…',
    retry: 'Try again',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    saved: 'Saved',
    saving: 'Saving…',
    back: 'Back',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    yes: 'Yes',
    no: 'No',
    optional: 'optional',
    units: { area: 'm²', currency: 'R' },
    help: 'How it works',
    menu: 'Menu',
    logout: 'Log out',
    offline: 'We could not reach the server. Check your connection and try again.',
    genericError: 'Something went wrong. Please try again.',
  },

  nav: {
    home: 'Find my house',
    recommendations: 'Recommendations',
    browse: 'Browse designs',
    saved: 'Saved plans',
    admin: 'Admin',
    login: 'Log in',
    register: 'Create account',
    loggedInAs: 'Logged in as',
  },

  auth: {
    loginTitle: 'Log in',
    loginIntro: 'Welcome back. Log in to see your recommendations and saved plans.',
    registerTitle: 'Create your account',
    registerIntro: 'It takes less than a minute. Then enter your plot and budget to get recommendations.',
    fullName: 'Full name',
    fullNamePlaceholder: 'e.g. Thandi Mokoena',
    email: 'Email address',
    emailPlaceholder: 'name@example.com',
    password: 'Password',
    passwordHint: 'At least 8 characters with a letter and a number.',
    confirmPassword: 'Confirm password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    loginButton: 'Log in',
    loggingIn: 'Logging in…',
    registerButton: 'Create account',
    registering: 'Creating your account…',
    noAccount: 'New here?',
    haveAccount: 'Already have an account?',
    demoTitle: 'Demo accounts',
    useDemo: 'Use',
    loggedOut: 'You have been logged out.',
    errors: {
      fullNameRequired: 'Please enter your full name.',
      fullNameShort: 'Your full name must be at least 2 characters.',
      emailRequired: 'Please enter your email address.',
      emailInvalid: 'That email address does not look right. Example: name@example.com',
      passwordRequired: 'Please enter your password.',
      passwordShort: 'Your password must be at least 8 characters long.',
      passwordWeak: 'Your password must contain at least one letter and one number.',
      passwordMismatch: 'The two passwords do not match.',
    },
  },

  dashboard: {
    title: 'Find my house',
    heading: 'What can you build on your plot?',
    intro: 'Tell us your plot size and construction budget. We will recommend house designs that fit and show what each one is likely to cost.',
    steps: ['Enter your plot size and budget', 'Compare recommended designs and their estimated costs', 'Open a design for its full cost breakdown and save your favourites'],
    plotSize: 'Plot size',
    plotSizeHint: 'The total area of your stand, in square metres.',
    plotPlaceholder: 'e.g. 400',
    budget: 'Construction budget',
    budgetHint: 'How much you can spend on building, in Rand.',
    budgetPlaceholder: 'e.g. 1 500 000',
    budgetPresets: 'Quick budget presets',
    filtersSummary: 'Optional filters (bedrooms, floors, style)',
    bedrooms: 'Minimum bedrooms',
    floors: 'Floors',
    style: 'Style',
    any: 'Any',
    submit: 'Find my house',
    submitting: 'Finding designs…',
    disabledReason: 'Enter a plot size and a budget to continue.',
    lastSearchRestored: 'We prefilled your last search. Change anything you like.',
    tooltips: {
      plot: 'Your house footprint may cover at most 50% of the plot, leaving room for a garden, parking and setbacks.',
      budget: 'Estimated cost = floor area × rate per m² for the finish level. Includes a 10% contingency.',
    },
    errors: {
      plotRequired: 'Please enter your plot size in m².',
      plotPositive: 'Plot size must be greater than 0 m².',
      plotTooBig: 'Plot size looks too large. Please check the number.',
      budgetRequired: 'Please enter your construction budget in Rand.',
      budgetPositive: 'Budget must be greater than R0.',
      budgetTooBig: 'Budget looks too large. Please check the number.',
    },
  },

  recommendations: {
    title: 'Recommendations',
    intro: 'Designs that fit your plot and budget, best match first.',
    searchSummary: 'Showing designs for a plot of {plot} and a budget of {budget}.',
    changeSearch: 'Change search',
    sortBy: 'Sort by',
    sortOptions: { match: 'Best match', costAsc: 'Cost: low to high', costDesc: 'Cost: high to low', areaDesc: 'Largest home' },
    filterBedrooms: 'Bedrooms',
    filterFloors: 'Floors',
    filterStyle: 'Style',
    resultCount: '{count} designs found',
    resultCountOne: '1 design found',
    noResultsTitle: 'No designs match yet',
    noResultsFilteredTitle: 'No designs match these filters',
    noResultsFilteredBody: 'Clear the filters below to see all recommended designs.',
    clearFilters: 'Clear filters',
    suggestionsTitle: 'What you can try',
    tryNewSearch: 'Try a new search',
    browseAll: 'Browse all designs',
    matchLabel: '{percent}% match',
    estimated: 'Estimated cost',
    from: 'from',
    to: 'to',
    viewDetails: 'View details',
    whyLabel: 'Why this design',
    nothingYet: 'You have not searched yet. Enter your plot size and budget to get recommendations.',
  },

  plan: {
    title: 'Plan details',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    floors: 'Floors',
    floorArea: 'Floor area',
    footprint: 'Footprint',
    minPlot: 'Minimum plot',
    style: 'Style',
    about: 'About this design',
    costTitle: 'Estimated construction cost',
    costIntro: 'Choose a finish level to see its breakdown. Estimates are indicative and exclude land, VAT and municipal fees.',
    finish: { basic: 'Basic', standard: 'Standard', premium: 'Premium' },
    finishDescriptions: {
      basic: 'Entry-level finishes: standard tiles, laminate counters, basic fittings.',
      standard: 'Mid-range finishes: porcelain tiles, granite counters, quality fittings.',
      premium: 'High-end finishes: imported tiles, stone counters, designer fittings.',
    },
    ratePerM2: '{rate} per m²',
    withinBudget: 'Within budget',
    overBudget: 'Over budget',
    breakdown: {
      structure: 'Structure (foundations, walls, roof)',
      finishes: 'Finishes (tiles, paint, joinery)',
      services: 'Services (plumbing, electrical)',
      professional_fees: 'Professional fees (architect, engineer)',
      contingency: 'Contingency (10%)',
      total: 'Total estimate',
    },
    whyTitle: 'Why this was recommended',
    whyNoContext: 'Open this design from your recommendations to see how it scores against your plot and budget.',
    scores: { budget_fit: 'Budget fit', plot_fit: 'Plot fit', area_utilisation: 'Home size' },
    scoreWeights: 'Match % = 50% budget fit + 30% plot fit + 20% home size.',
    bestFinish: 'Best finish you can afford',
    budgetLeft: 'left in your budget',
    plotCoverage: 'of your plot covered',
    backToResults: 'Back to recommendations',
    notFound: 'This house plan is no longer available.',
    saveTooltip: 'Keep this design in your saved list.',
    savedTooltip: 'Remove this design from your saved list.',
    loginToSave: 'Log in to save designs.',
  },

  browse: {
    title: 'Browse designs',
    intro: 'Search all active house designs. Estimated costs use the current rates.',
    search: 'Search',
    searchPlaceholder: 'Search by name, style or description',
    bedrooms: 'Min. bedrooms',
    floors: 'Floors',
    style: 'Style',
    maxArea: 'Max floor area',
    apply: 'Apply filters',
    clear: 'Clear',
    results: '{count} designs',
    resultsOne: '1 design',
    noResultsTitle: 'No designs found',
    noResultsBody: 'Try a different search term or clear the filters.',
  },

  saved: {
    title: 'Saved plans',
    intro: 'Designs you have saved. Open one for its full cost breakdown.',
    emptyTitle: 'No saved plans yet',
    emptyBody: 'Tap "Save" on any design to keep it here for later.',
    findDesigns: 'Find designs',
    remove: 'Remove',
    removed: 'Removed from your saved plans.',
    undo: 'Undo',
  },

  admin: {
    title: 'Admin dashboard',
    intro: 'Manage house plans, users and cost rates.',
    tabs: { plans: 'House plans', users: 'Users', rates: 'Cost rates' },
    stats: { users: 'Users', active_plans: 'Active plans', searches: 'Searches run', saved_plans: 'Plans saved' },
    plans: {
      add: 'Add house plan',
      edit: 'Edit house plan',
      name: 'Name',
      description: 'Description',
      bedrooms: 'Bedrooms',
      bathrooms: 'Bathrooms',
      floors: 'Floors',
      floorArea: 'Floor area',
      footprint: 'Footprint',
      minPlot: 'Minimum plot size',
      style: 'Style',
      imageUrl: 'Image URL',
      imageHint: 'Leave empty to show a placeholder.',
      active: 'Visible to clients',
      activeHint: 'Hidden plans are never recommended but keep their saved history.',
      status: 'Status',
      visible: 'Visible',
      hidden: 'Hidden',
      hide: 'Hide',
      show: 'Show',
      create: 'Add plan',
      update: 'Save changes',
      deleteTitle: 'Delete this house plan?',
      deleteBody: '"{name}" will be removed permanently, including from every user\'s saved list. You cannot undo this. If you only want to stop recommending it, choose "Hide" instead.',
      deleteConfirm: 'Yes, delete it',
      emptyTitle: 'No house plans yet',
      emptyBody: 'Add your first house plan to start recommending designs.',
      estimateFrom: 'Basic estimate',
    },
    users: {
      name: 'Name',
      email: 'Email',
      role: 'Role',
      status: 'Status',
      joined: 'Joined',
      active: 'Active',
      inactive: 'Deactivated',
      deactivate: 'Deactivate',
      reactivate: 'Reactivate',
      deactivateTitle: 'Deactivate this user?',
      deactivateBody: '{name} will no longer be able to log in. You can reactivate them later.',
      deactivateConfirm: 'Yes, deactivate',
      you: 'you',
      cannotDeactivateSelf: 'You cannot deactivate your own account.',
    },
    rates: {
      intro: 'Rates are Rand per square metre of floor area. Changing a rate updates every estimate immediately.',
      rate: 'Rate per m²',
      updated: 'Last updated',
      save: 'Save rate',
      unchanged: 'No change to save',
    },
    confirmDiscardTitle: 'Discard your changes?',
    confirmDiscardBody: 'You have unsaved changes in this form. Closing will lose them.',
    discard: 'Discard',
    keepEditing: 'Keep editing',
  },

  help: {
    title: 'How it works',
    sections: [
      {
        heading: 'What we need from you',
        items: ['Your plot size in square metres (m²).', 'Your construction budget in Rand (R).', 'Optionally: bedrooms, floors and a style.'],
      },
      {
        heading: 'How designs are chosen',
        items: [
          'A design must fit your plot: its footprint may cover at most 50% of the plot, and the plot must meet the design\'s minimum size.',
          'A design must be affordable at its basic finish level.',
          'Each design gets a match score: 50% budget fit, 30% plot fit, 20% home size.',
        ],
      },
      {
        heading: 'How costs are estimated',
        items: [
          'Estimated cost = floor area × rate per m² for the chosen finish (basic, standard or premium).',
          'The breakdown splits this into structure, finishes, services, professional fees and a 10% contingency.',
          'Estimates exclude land, VAT and municipal connection fees. Always confirm with a quantity surveyor.',
        ],
      },
      {
        heading: 'Tips',
        items: ['Your last search is remembered so you can pick up where you left off.', 'Save designs to compare them later under "Saved plans".'],
      },
    ],
    currentRates: 'Current rates',
  },

  notFound: {
    title: 'Page not found',
    body: 'The page you are looking for does not exist or has moved.',
    goHome: 'Go to Find my house',
  },

  breadcrumbs: {
    home: 'Home',
  },
};

/**
 * Tiny template helper: fill("{a} and {b}", { a: 1, b: 2 }).
 * @param {string} template
 * @param {Record<string, string|number>} values
 */
export function fill(template, values = {}) {
  return template.replace(/\{(\w+)\}/g, (_, key) => (values[key] !== undefined ? String(values[key]) : `{${key}}`));
}
